### ISSUE TITLE
Add style for section breaks

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#1]
Add new break style: Section Break, add to workflow processes requiring CE/PE to style a section break paragraph between every new section (titlepage, copyright page, chapter, appendix, etc). Additionally this as a check in the styles reporter macro, to check if section breaks are present, and if they are not, to issue a warning.

**Comment by ericawarren** [comment]
Page break used for this, check for appropriate page breaks added to template v. 3.9
