### ISSUE TITLE
New style: Titlepage logo (logo)

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#144]
Let's add a new paragraph style for tagging the titlepage logo. Content of the paragraph can be anything (we'll strip it out and replace with the correct image). Documentation will also need to be updated, and we'll need to send a note out to all users and to Westchester about the change.

**Comment by ericawarren** [comment]
Deadline for name of style? Deadline for rollout of new style?

**Comment by nelliemckesson** [comment]
I'd like to use this process for the flatiron RBMs, so the sooner the better. What's reasonable? I know you just released an update, but if the auto-updating is working, I'd rather get this released within a week or so. If auto-updating isn't working, I don't want to force people to manually update for just one new style.
