### ISSUE TITLE
add some kind of "span other text formatting" character style

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/Word-template#151]
Per request from PE (Jill Freshney), for tagging any random run-in text formatting that may be needed on the fly.

**Comment by ericawarren** [comment]
Also have to update Character Styles Macro and Style/Bookmaker Report macros to preserve text tagged with this style.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:
Can use new "span font 1" and "span font 2" for non-Tor Bookmaker uses.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:
Closed with version 3.0.8
