### ISSUE TITLE
Frames in MS breaks cleanup macro

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/Word-template#174]
From Westchester: "We noticed that some of the recent files for pre-edit that we have received are composed using frames in the running text. Due to the usage of frames, the Macmillan clean-up script do not run beyond certain percentage."

[Text Fames_screenshot.docx](https://github.com/macmillanpublishers/Word-template/files/189604/Text.Fames_screenshot.docx)

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:
Closed with version 3.0.8
