### ISSUE TITLE
Migration from Word 2007 to Word 2013

### ISSUE THREAD

**Issue by senthilmm** [macmillanpublishers/Word-template#200]
Do you foresee any issues while using 2013 template in Office 2007?

**Comment by ericawarren** [comment]
Hi! Our users have been working with Word 2010 for a while, and we've been using Word 2013 as our primary development platform for over a year.  Also our users are in the process of moving to Word 2013, so we'll be prioritizing that version moving forward.

That being said, we've tested the template on Windows 7 and a little on 8.1, but have not tested extensively Windows 10, if that's an issue.

**Comment by senthilmm** [comment]
Thanks.
