### ISSUE TITLE
Installing the template for new users

### ISSUE THREAD

**Issue by senthilmm** [macmillanpublishers/Word-template#204]
A new installation creates "MacmillanStyleTemplate" folder in AppData/Roaming/. On launching Word, Macmillan Tools Version and Macmillan Styles Version reports "You do not have MacmillanGT.dotm/macmillan.dotm installed on your computer".

Copying "MacmillanStyleTemplate" folder to ProgramData resolves this issue. Any thoughts.

Tested on Windows 10 Pro x64-based PC.

**Comment by senthilmm** [comment]
CheckMacmillanGT() and CheckMacmillan() requires the following change
       ' strTemplatePath = Environ("PROGRAMDATA") & "\MacmillanStyleTemplate\" & templateFile
       strTemplatePath = Environ("APPDATA") & "\MacmillanStyleTemplate\" & templateFile

**Comment by ericawarren** [comment]
Thanks for the details! I'll take a look at this for our next update.
