### ISSUE TITLE
[ss] Remove epigraph handling

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#215]
Remove the extra handling that finds and retags epigraphs, as that will be evident with the new section-start styles.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

This is really a subtask of https://app.asana.com/0/217471178799090/290911667688594, since we are only removing for new-format sections.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

Pushing back as this is only relevant to bookmaker_validator, not user macros

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:

Closing as we're moving validator to Python, no longer relevant
