### ISSUE TITLE
[ss] Create section-head validation rules

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#217]
Come up with the rules that dictate how to identify new sections, and where to insert the section-start styles if they are missing. Additionally, we'll need rules for how to handle adding headings for sections that don't have titles (for EPUB).

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:
These are the rules that are now maintained in a JSON file in bookmaker_validator
