### ISSUE TITLE
[ss] Create JSON to store section-head rules

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#218]
Store the new section-head rules in a JSON file that will be read by both the VBA and JS scripts.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
This is created; the mock-up here: https://docs.google.com/spreadsheets/d/1CBsk8kJLgy8PGsjTbmjT5KJO2Cg30x_4i3Tjt-7JQI0/edit#gid=2123523468
and an actual json of same in a branch I have for the validator:  https://github.com/macmillanpublishers/bookmaker_validator/blob/rulesjson/ss_rules.json

https://app.asana.com/0/142682776454805/142682776454805 and https://app.asana.com/0/142682204252343/142682204252343..  is the root of bookmaker_validator an ok place for this json to live?  Any further changes you wanted me to make to the form/format/nomenclature?  (Don't feel like you _need_ to come up with a change, cuz I've already started to build around it ;)

**Comment by ericawarren** [comment]
I'm OK with the JSON living in bookmaker_validator. I'll need to create a config file for it at some point, since that is how the Word-template will download/update it for users and locate it in the local installation.

**Comment by nelliemckesson** [comment]
Yeah I think it makes sense in validator. Make sure you reference it in a way that it's easy to move it if we decide we want to, though.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
OK, I am submitting a PR for bookmake_validator shortly, including the JSON... and closing this issue in the meantime

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Here is the PR including this: https://github.com/macmillanpublishers/bookmaker_validator/pull/97
