### ISSUE TITLE
Error: "Object variable or With block variable not set"

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/Word-template#85]
Just received this error when running Bookmaker Check on the sample from Digital Marketing:

![screen shot 2015-07-07 at 1 56 21 pm](https://cloud.githubusercontent.com/assets/812739/8553250/1bcd2112-24b0-11e5-8482-be9d4aaa5e39.png)

**Comment by ericawarren** [comment]
Fixed with pull request #87
